### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by uli-objectbox** [RobotsAndPencils/stencil-xclangspec#1]
Hi, thanks for making this available publicly!

I just ran the install script and it copied the file(s) all right, but Xcode 10.3 doesn't seem to pick up the language spec (or at least I see no colors for the .stencil file in my project). Stencil Template also doesn't show up in the file type popup of the File inspector either.

Am I missing how this is supposed to work? Is there some extra setup I need to do? Or are language specs only picked up by older Xcode versions before 10?

**Comment by interstateone** [comment]
Hey @uli-objectbox! Thanks for opening this issue. You're not misunderstanding how this should work or missing any steps, and I apologize that this project wasn't working for you. If you download the latest version of the project, or pull the master branch if you're using git, running ./setup.sh again should install some changes that allow the plugin to work with Xcode 10.3 (and 10.2.1). Please let me know if that doesn't solve the issue for you. It worked for me when I tested it.

Some background: Xcode will only attempt to load an .ideplugin if its Info.plist contains a UUID that matches the DVTPlugInCompatibilityUUID value in the Xcode's Info.plist. This UUID changes with each version of Xcode, so plugin authors need to keep adding UUIDs for each new Xcode that's released. I failed to do that for this project for 10.2.1 and 10.3. This was resolved with #2 

In my experience Xcode 11 betas will _not_ support user-installed .xclangspecs, even though it loads the .ideplugin and supports the defined filetype, so this solution won't support those versions.

**Comment by uli-objectbox** [comment]
BTW - Might be worth mentioning this in the Readme or so, then people who run into it can ad the UUID themselves and send you a pull request.

Of course, if Xcode 11 really drops support, that'll be irrelevant XD
